### ISSUE TITLE
Add redirect field to Python operations

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-catalogs#319]
**What problem is your feature request trying to solve?**
In https://github.com/MobilityData/mobility-database-catalogs/pull/309, redirect was added to the schema and CSV, but not the [Python operations](https://github.com/MobilityData/mobility-database-catalogs/blob/main/tools/operations.py). That means right now, if I want to add redirect and still generate the right bounding box I need to

Add a feed via the add_gtfs_schedule_source or add_gtfs_realtime_source operations
Push PR
Modify JSON to include redirect directly
Update PR
rather than add all fields through the operations.

**Describe the solution you'd like**
Include redirect in Python operations, to add and update gtfs schedule and gtfs realtime feeds.
Include redirect object in schema in README

**Comment by emmambd** [comment]
@cka-y Looks like the test is validating for a string value, when redirect is a number: https://github.com/MobilityData/mobility-database-catalogs/commit/4b71837339c26728d51161676ae6609907d683b5#diff-92300112b36301d0886c9786601b64e36393c1ae3dd25102b2ce3af4cfb72795.

**Comment by emmambd** [comment]
@cka-y Looks like this is breaking Fred's script: 

> Traceback (most recent call last):
> 46  File "<string>", line 2, in <module>
> 47  File "/home/runner/work/mobility-database-catalogs/mobility-database-catalogs/tools/operations.py", line 142, in add_gtfs_schedule_source
> 48    catalog.add(**data)
> 49  File "/home/runner/work/mobility-database-catalogs/mobility-database-catalogs/tools/representations.py", line 168, in add
> 50    if len(redirects) > 0:
> 51       ^^^^^^^^^^^^^^
> 52 TypeError: object of type 'NoneType' has no len()

Are the operations not set up to take the redirect as an optional field? The script run we did last night had 0 redirect fields populated.
